apiVersion: v1

kind: Pod

metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    app: learning-k8s

spec:
  containers:
    - name: database
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'root'
        - name: MYSQL_DATABASE
          value: 'mydefaultdatabase'
