apiVersion: v1

kind: Pod

metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
    app: learning-k8s

spec:
  containers:
    - name: web-server
      image: nginx:stable
      ports:
        - containerPort: 80
