apiVersion: v1

kind: Service

metadata:
  name: mysql-service
  labels:
    name: mysql-service
    app: learning-k8s

spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql-pod
    app: learning-k8s
