version: '3.9'

networks:
  common:
    driver: bridge

services:
  mysqldb:
    image: mysql
    container_name: database
    restart: always
    networks:
      - common
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydefaultdatabase

  nginxwebserver:
    image: nginx:stable
    container_name: webserver
    restart: always
    networks:
      - common
    ports:
      - 80:80
    volumes:
      - ./www:/www
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - mysqldb
